
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class demo_category extends javax.swing.JFrame {

    /**
     * Creates new form demo_category
     */
    public demo_category() {
        initComponents();
        setSize(620, 542);
        loadcategory();
    }
     void loadcategory()
    {
        String ans= myClient.fetchcat();
        System.out.println(ans);
        StringTokenizer st=new StringTokenizer(ans,";;");
        int n=st.countTokens();
        //System.out.println(n);
        JButton arr[]=new JButton[n];
        int x=15,y=100;
        for(int i=0;i<n;i++)
        {
           String row =st.nextToken();
           StringTokenizer st1=new StringTokenizer(row,"$");
           String name=st1.nextToken();
           //category=name;
           String photo=st1.nextToken(); 
           arr[i]=new JButton(name);
           
//           ImageIcon ic= new ImageIcon(photo);
//           Image img= ic.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
//           ImageIcon ic1= new ImageIcon(img);
//           
           arr[i].setIcon(new ImageIcon(photo));
//             arr[i].setIcon(ic1);
           arr[i].setBounds(x, y, 130, 40);
           arr[i].addActionListener(new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
                   
                 //  JOptionPane.showMessageDialog(rootPane, "add moveies");
                 //fetch_movies obj=new fetch_movies(name);
                 demo obj=new demo();
                 obj.setVisible(true);
                 dispose();
                 
               }
           });
           mainpanel.add(arr[i]);
           mainpanel.repaint(); //resrech thev panel
           if(x<=255)
           {
             x=x+130;  
           }
           else
           {
               x=15;
               y=y+50;
           }
           
           
        }
        mainpanel.setPreferredSize(new Dimension(450,n*50));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Search cayegory");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(7, 16, 130, 50);

        tf1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf1CaretUpdate(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(180, 30, 400, 30);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 460, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf1CaretUpdate
        // TODO add your handling code here:
        loadcategory();
    }//GEN-LAST:event_tf1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo_category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo_category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo_category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo_category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo_category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
