
import java.awt.*;
import static java.awt.Color.*;
import java.io.File;
import javax.swing.*;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class usersignup extends javax.swing.JFrame 
{
    //JFileChooser jfc;
    //File ph;

    /**
     * Creates new form usersignup
     */
    public usersignup() 
    {
       
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(680,600);
        ImageIcon ic=new ImageIcon("src/signupjpeg.jpeg");
        Image im=ic.getImage().getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(im));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pf = new javax.swing.JPasswordField();
        mob = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER SIGNUP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 530, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 200, 0);

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 126, 200, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 200, 0);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("mobile");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 250, 80, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 100, 100, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 180, 80, 30);

        pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfActionPerformed(evt);
            }
        });
        getContentPane().add(pf);
        pf.setBounds(190, 180, 260, 30);
        getContentPane().add(mob);
        mob.setBounds(190, 250, 260, 30);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 310, 370, 60);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Already have an account?");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 400, 180, 30);

        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        getContentPane().add(email1);
        email1.setBounds(190, 100, 260, 30);

        jLabel6.setText("By signing in, you agree to the VOD Terms of Use");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 440, 320, 30);

        jLabel9.setText("and licence agreements which can be found on ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 470, 260, 30);

        jLabel12.setText("VOD website");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 504, 250, 20);
        getContentPane().add(background);
        background.setBounds(0, 0, 680, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String email=email1.getText();
        String password=pf.getText();
        String mobile=mob.getText();
       // String add =address.getText();
        if(email.equals(" ")|| password.equals(" ")|| mobile.equals(" "))
        {
            JOptionPane.showMessageDialog(rootPane, "all feilds are mendatatory");
        }
        else 
        {
            String ans=myClient.verifyemail(email);
            if(ans.equals("exist"))
            {
               JOptionPane.showMessageDialog(rootPane, "email already exist"); 
            }
            else
            {
                otp_send obj=new otp_send(email,password,mobile,ans);
                obj.setVisible(true);
               dispose();
             }

        }
               /*
        else
        {
            String ans=myClient.verifyemail(email);
            if(ans.equals("exist"))
            {
                JOptionPane.showMessageDialog(rootPane, "email already exist");

            }
           
            
            else 
            {
               System.out.println(ans);
               String otp= JOptionPane.showInputDialog(rootPane, "ENTER OTP FOR VERIFY");
               if(otp.trim().equals(ans.trim()))
               {
                   String ans1=myClient.usersignup(email, password, phone);
                   //System.out.println(ans1);
                   if(ans1.equals("sucess"))
                   {
                      JOptionPane.showMessageDialog(rootPane, "signup sucessfully");
                      userlogin obj=new userlogin();
                      obj.setVisible(true);
                      dispose();
                   }
                   else if(ans1.equals("mobile"))
                   {
                     JOptionPane.showMessageDialog(rootPane, "mobile number  already exist");
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(rootPane, "signup failed");

                   }
            
               }
               else
               {
                  JOptionPane.showMessageDialog(rootPane, "OTP NOT MATCHED");
               }
            }
        
            
            
           
        }
*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfActionPerformed

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         userlogin obj=new userlogin();
         obj.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField email1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mob;
    private javax.swing.JPasswordField pf;
    // End of variables declaration//GEN-END:variables
}
