
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(600,600);
        ImageIcon ic=new ImageIcon("src/wlecome.jpeg");
        Image im=ic.getImage().getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(im));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminlogin = new javax.swing.JButton();
        signup1 = new javax.swing.JButton();
        signup2 = new javax.swing.JButton();
        signup3 = new javax.swing.JButton();
        signup4 = new javax.swing.JButton();
        signup5 = new javax.swing.JButton();
        signup6 = new javax.swing.JButton();
        signup7 = new javax.swing.JButton();
        signup8 = new javax.swing.JButton();
        signup9 = new javax.swing.JButton();
        signup10 = new javax.swing.JButton();
        signup11 = new javax.swing.JButton();
        signup12 = new javax.swing.JButton();
        signup13 = new javax.swing.JButton();
        signup14 = new javax.swing.JButton();
        signup15 = new javax.swing.JButton();
        signup16 = new javax.swing.JButton();
        signup17 = new javax.swing.JButton();
        signup18 = new javax.swing.JButton();
        signup19 = new javax.swing.JButton();
        signup20 = new javax.swing.JButton();
        signup21 = new javax.swing.JButton();
        signup22 = new javax.swing.JButton();
        signup23 = new javax.swing.JButton();
        signup24 = new javax.swing.JButton();
        signup25 = new javax.swing.JButton();
        signup26 = new javax.swing.JButton();
        signup27 = new javax.swing.JButton();
        signup28 = new javax.swing.JButton();
        signup29 = new javax.swing.JButton();
        signup30 = new javax.swing.JButton();
        signup31 = new javax.swing.JButton();
        signup32 = new javax.swing.JButton();
        signup33 = new javax.swing.JButton();
        signup34 = new javax.swing.JButton();
        signup35 = new javax.swing.JButton();
        signup36 = new javax.swing.JButton();
        signup37 = new javax.swing.JButton();
        signup38 = new javax.swing.JButton();
        signup39 = new javax.swing.JButton();
        signup40 = new javax.swing.JButton();
        signup41 = new javax.swing.JButton();
        signup42 = new javax.swing.JButton();
        signup43 = new javax.swing.JButton();
        signup44 = new javax.swing.JButton();
        signup45 = new javax.swing.JButton();
        signup46 = new javax.swing.JButton();
        signup47 = new javax.swing.JButton();
        signup48 = new javax.swing.JButton();
        signup49 = new javax.swing.JButton();
        signup50 = new javax.swing.JButton();
        signup51 = new javax.swing.JButton();
        signup52 = new javax.swing.JButton();
        signup53 = new javax.swing.JButton();
        signup54 = new javax.swing.JButton();
        signup55 = new javax.swing.JButton();
        signup56 = new javax.swing.JButton();
        signup57 = new javax.swing.JButton();
        signup58 = new javax.swing.JButton();
        signup59 = new javax.swing.JButton();
        signup60 = new javax.swing.JButton();
        signup61 = new javax.swing.JButton();
        signup62 = new javax.swing.JButton();
        signup63 = new javax.swing.JButton();
        signup64 = new javax.swing.JButton();
        signup65 = new javax.swing.JButton();
        signup66 = new javax.swing.JButton();
        signup67 = new javax.swing.JButton();
        signup68 = new javax.swing.JButton();
        signup69 = new javax.swing.JButton();
        signup70 = new javax.swing.JButton();
        signup71 = new javax.swing.JButton();
        signup72 = new javax.swing.JButton();
        signup73 = new javax.swing.JButton();
        signup74 = new javax.swing.JButton();
        signup75 = new javax.swing.JButton();
        signup76 = new javax.swing.JButton();
        signup77 = new javax.swing.JButton();
        signup78 = new javax.swing.JButton();
        signup79 = new javax.swing.JButton();
        signup80 = new javax.swing.JButton();
        signup81 = new javax.swing.JButton();
        signup82 = new javax.swing.JButton();
        signup83 = new javax.swing.JButton();
        signup84 = new javax.swing.JButton();
        signup85 = new javax.swing.JButton();
        signup86 = new javax.swing.JButton();
        signup87 = new javax.swing.JButton();
        signup88 = new javax.swing.JButton();
        signup89 = new javax.swing.JButton();
        signup90 = new javax.swing.JButton();
        signup91 = new javax.swing.JButton();
        signup92 = new javax.swing.JButton();
        signup93 = new javax.swing.JButton();
        signup94 = new javax.swing.JButton();
        signup95 = new javax.swing.JButton();
        signup96 = new javax.swing.JButton();
        signup97 = new javax.swing.JButton();
        signup98 = new javax.swing.JButton();
        signup99 = new javax.swing.JButton();
        signup100 = new javax.swing.JButton();
        signup101 = new javax.swing.JButton();
        signup102 = new javax.swing.JButton();
        signup103 = new javax.swing.JButton();
        signup104 = new javax.swing.JButton();
        signup105 = new javax.swing.JButton();
        signup106 = new javax.swing.JButton();
        signup107 = new javax.swing.JButton();
        signup108 = new javax.swing.JButton();
        signup109 = new javax.swing.JButton();
        signup110 = new javax.swing.JButton();
        signup111 = new javax.swing.JButton();
        signup112 = new javax.swing.JButton();
        signup113 = new javax.swing.JButton();
        signup114 = new javax.swing.JButton();
        signup115 = new javax.swing.JButton();
        signup116 = new javax.swing.JButton();
        signup117 = new javax.swing.JButton();
        signup118 = new javax.swing.JButton();
        signup119 = new javax.swing.JButton();
        signup120 = new javax.swing.JButton();
        signup121 = new javax.swing.JButton();
        signup122 = new javax.swing.JButton();
        signup123 = new javax.swing.JButton();
        signup124 = new javax.swing.JButton();
        signup125 = new javax.swing.JButton();
        signup126 = new javax.swing.JButton();
        signup127 = new javax.swing.JButton();
        signup128 = new javax.swing.JButton();
        signup129 = new javax.swing.JButton();
        signup130 = new javax.swing.JButton();
        signup131 = new javax.swing.JButton();
        signup132 = new javax.swing.JButton();
        signup133 = new javax.swing.JButton();
        signup134 = new javax.swing.JButton();
        signup135 = new javax.swing.JButton();
        signup136 = new javax.swing.JButton();
        signup137 = new javax.swing.JButton();
        signup138 = new javax.swing.JButton();
        signup139 = new javax.swing.JButton();
        signup140 = new javax.swing.JButton();
        signup141 = new javax.swing.JButton();
        signup142 = new javax.swing.JButton();
        signup143 = new javax.swing.JButton();
        signup144 = new javax.swing.JButton();
        signup145 = new javax.swing.JButton();
        signup146 = new javax.swing.JButton();
        signup147 = new javax.swing.JButton();
        signup148 = new javax.swing.JButton();
        signup149 = new javax.swing.JButton();
        signup150 = new javax.swing.JButton();
        signup151 = new javax.swing.JButton();
        signup152 = new javax.swing.JButton();
        signup153 = new javax.swing.JButton();
        signup154 = new javax.swing.JButton();
        signup155 = new javax.swing.JButton();
        signup156 = new javax.swing.JButton();
        signup157 = new javax.swing.JButton();
        signup158 = new javax.swing.JButton();
        signup159 = new javax.swing.JButton();
        signup160 = new javax.swing.JButton();
        signup161 = new javax.swing.JButton();
        signup162 = new javax.swing.JButton();
        signup163 = new javax.swing.JButton();
        signup164 = new javax.swing.JButton();
        signup165 = new javax.swing.JButton();
        signup166 = new javax.swing.JButton();
        signup167 = new javax.swing.JButton();
        signup168 = new javax.swing.JButton();
        signup169 = new javax.swing.JButton();
        signup170 = new javax.swing.JButton();
        signup171 = new javax.swing.JButton();
        signup172 = new javax.swing.JButton();
        signup173 = new javax.swing.JButton();
        signup174 = new javax.swing.JButton();
        signup175 = new javax.swing.JButton();
        signup176 = new javax.swing.JButton();
        signup177 = new javax.swing.JButton();
        signup178 = new javax.swing.JButton();
        signup179 = new javax.swing.JButton();
        signup180 = new javax.swing.JButton();
        signup181 = new javax.swing.JButton();
        signup182 = new javax.swing.JButton();
        signup183 = new javax.swing.JButton();
        signup184 = new javax.swing.JButton();
        signup185 = new javax.swing.JButton();
        signup186 = new javax.swing.JButton();
        signup187 = new javax.swing.JButton();
        signup188 = new javax.swing.JButton();
        signup189 = new javax.swing.JButton();
        signup190 = new javax.swing.JButton();
        signup191 = new javax.swing.JButton();
        signup192 = new javax.swing.JButton();
        signup193 = new javax.swing.JButton();
        signup194 = new javax.swing.JButton();
        signup195 = new javax.swing.JButton();
        signup196 = new javax.swing.JButton();
        signup197 = new javax.swing.JButton();
        signup198 = new javax.swing.JButton();
        signup199 = new javax.swing.JButton();
        signup200 = new javax.swing.JButton();
        signup201 = new javax.swing.JButton();
        signup202 = new javax.swing.JButton();
        signup203 = new javax.swing.JButton();
        signup204 = new javax.swing.JButton();
        userlogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        adminlogin.setBackground(new java.awt.Color(102, 102, 102));
        adminlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(204, 204, 204));
        adminlogin.setText("ADMIN LOGIN");
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin);
        adminlogin.setBounds(15, 190, 180, 90);

        signup1.setText("SIGN UP");
        getContentPane().add(signup1);
        signup1.setBounds(15, 190, 170, 90);

        signup2.setText("SIGN UP");
        getContentPane().add(signup2);
        signup2.setBounds(15, 190, 170, 90);

        signup3.setText("SIGN UP");
        getContentPane().add(signup3);
        signup3.setBounds(15, 190, 170, 90);

        signup4.setText("SIGN UP");
        getContentPane().add(signup4);
        signup4.setBounds(15, 190, 170, 90);

        signup5.setText("SIGN UP");
        getContentPane().add(signup5);
        signup5.setBounds(15, 190, 170, 90);

        signup6.setText("SIGN UP");
        getContentPane().add(signup6);
        signup6.setBounds(15, 190, 170, 90);

        signup7.setText("SIGN UP");
        getContentPane().add(signup7);
        signup7.setBounds(15, 190, 170, 90);

        signup8.setText("SIGN UP");
        getContentPane().add(signup8);
        signup8.setBounds(15, 190, 170, 90);

        signup9.setText("SIGN UP");
        getContentPane().add(signup9);
        signup9.setBounds(15, 190, 170, 90);

        signup10.setText("SIGN UP");
        getContentPane().add(signup10);
        signup10.setBounds(15, 190, 170, 90);

        signup11.setText("SIGN UP");
        getContentPane().add(signup11);
        signup11.setBounds(15, 190, 170, 90);

        signup12.setText("SIGN UP");
        getContentPane().add(signup12);
        signup12.setBounds(15, 190, 170, 90);

        signup13.setText("SIGN UP");
        getContentPane().add(signup13);
        signup13.setBounds(15, 190, 170, 90);

        signup14.setText("SIGN UP");
        getContentPane().add(signup14);
        signup14.setBounds(15, 190, 170, 90);

        signup15.setText("SIGN UP");
        getContentPane().add(signup15);
        signup15.setBounds(15, 190, 170, 90);

        signup16.setText("SIGN UP");
        getContentPane().add(signup16);
        signup16.setBounds(15, 190, 170, 90);

        signup17.setText("SIGN UP");
        getContentPane().add(signup17);
        signup17.setBounds(15, 190, 170, 90);

        signup18.setText("SIGN UP");
        getContentPane().add(signup18);
        signup18.setBounds(15, 190, 170, 90);

        signup19.setText("SIGN UP");
        getContentPane().add(signup19);
        signup19.setBounds(15, 190, 170, 90);

        signup20.setText("SIGN UP");
        getContentPane().add(signup20);
        signup20.setBounds(15, 190, 170, 90);

        signup21.setText("SIGN UP");
        getContentPane().add(signup21);
        signup21.setBounds(15, 190, 170, 90);

        signup22.setText("SIGN UP");
        getContentPane().add(signup22);
        signup22.setBounds(15, 190, 170, 90);

        signup23.setText("SIGN UP");
        getContentPane().add(signup23);
        signup23.setBounds(15, 190, 170, 90);

        signup24.setText("SIGN UP");
        getContentPane().add(signup24);
        signup24.setBounds(15, 190, 170, 90);

        signup25.setText("SIGN UP");
        getContentPane().add(signup25);
        signup25.setBounds(15, 190, 170, 90);

        signup26.setText("SIGN UP");
        getContentPane().add(signup26);
        signup26.setBounds(15, 190, 170, 90);

        signup27.setText("SIGN UP");
        getContentPane().add(signup27);
        signup27.setBounds(15, 190, 170, 90);

        signup28.setText("SIGN UP");
        getContentPane().add(signup28);
        signup28.setBounds(15, 190, 170, 90);

        signup29.setText("SIGN UP");
        getContentPane().add(signup29);
        signup29.setBounds(15, 190, 170, 90);

        signup30.setText("SIGN UP");
        getContentPane().add(signup30);
        signup30.setBounds(15, 190, 170, 90);

        signup31.setText("SIGN UP");
        getContentPane().add(signup31);
        signup31.setBounds(15, 190, 170, 90);

        signup32.setText("SIGN UP");
        getContentPane().add(signup32);
        signup32.setBounds(15, 190, 170, 90);

        signup33.setText("SIGN UP");
        getContentPane().add(signup33);
        signup33.setBounds(15, 190, 170, 90);

        signup34.setText("SIGN UP");
        getContentPane().add(signup34);
        signup34.setBounds(15, 190, 170, 90);

        signup35.setText("SIGN UP");
        getContentPane().add(signup35);
        signup35.setBounds(15, 190, 170, 90);

        signup36.setText("SIGN UP");
        getContentPane().add(signup36);
        signup36.setBounds(15, 190, 170, 90);

        signup37.setText("SIGN UP");
        getContentPane().add(signup37);
        signup37.setBounds(15, 190, 170, 90);

        signup38.setText("SIGN UP");
        getContentPane().add(signup38);
        signup38.setBounds(15, 190, 170, 90);

        signup39.setText("SIGN UP");
        getContentPane().add(signup39);
        signup39.setBounds(15, 190, 170, 90);

        signup40.setText("SIGN UP");
        getContentPane().add(signup40);
        signup40.setBounds(15, 190, 170, 90);

        signup41.setText("SIGN UP");
        getContentPane().add(signup41);
        signup41.setBounds(15, 190, 170, 90);

        signup42.setText("SIGN UP");
        getContentPane().add(signup42);
        signup42.setBounds(15, 190, 170, 90);

        signup43.setText("SIGN UP");
        getContentPane().add(signup43);
        signup43.setBounds(15, 190, 170, 90);

        signup44.setText("SIGN UP");
        getContentPane().add(signup44);
        signup44.setBounds(15, 190, 170, 90);

        signup45.setText("SIGN UP");
        getContentPane().add(signup45);
        signup45.setBounds(15, 190, 170, 90);

        signup46.setText("SIGN UP");
        getContentPane().add(signup46);
        signup46.setBounds(15, 190, 170, 90);

        signup47.setText("SIGN UP");
        getContentPane().add(signup47);
        signup47.setBounds(15, 190, 170, 90);

        signup48.setText("SIGN UP");
        getContentPane().add(signup48);
        signup48.setBounds(15, 190, 170, 90);

        signup49.setText("SIGN UP");
        getContentPane().add(signup49);
        signup49.setBounds(15, 190, 170, 90);

        signup50.setText("SIGN UP");
        getContentPane().add(signup50);
        signup50.setBounds(15, 190, 170, 90);

        signup51.setText("SIGN UP");
        getContentPane().add(signup51);
        signup51.setBounds(15, 190, 170, 90);

        signup52.setText("SIGN UP");
        getContentPane().add(signup52);
        signup52.setBounds(15, 190, 170, 90);

        signup53.setText("SIGN UP");
        getContentPane().add(signup53);
        signup53.setBounds(15, 190, 170, 90);

        signup54.setText("SIGN UP");
        getContentPane().add(signup54);
        signup54.setBounds(15, 190, 170, 90);

        signup55.setText("SIGN UP");
        getContentPane().add(signup55);
        signup55.setBounds(15, 190, 170, 90);

        signup56.setText("SIGN UP");
        getContentPane().add(signup56);
        signup56.setBounds(15, 190, 170, 90);

        signup57.setText("SIGN UP");
        getContentPane().add(signup57);
        signup57.setBounds(15, 190, 170, 90);

        signup58.setText("SIGN UP");
        getContentPane().add(signup58);
        signup58.setBounds(15, 190, 170, 90);

        signup59.setText("SIGN UP");
        getContentPane().add(signup59);
        signup59.setBounds(15, 190, 170, 90);

        signup60.setText("SIGN UP");
        getContentPane().add(signup60);
        signup60.setBounds(15, 190, 170, 90);

        signup61.setText("SIGN UP");
        getContentPane().add(signup61);
        signup61.setBounds(15, 190, 170, 90);

        signup62.setText("SIGN UP");
        getContentPane().add(signup62);
        signup62.setBounds(15, 190, 170, 90);

        signup63.setText("SIGN UP");
        getContentPane().add(signup63);
        signup63.setBounds(15, 190, 170, 90);

        signup64.setText("SIGN UP");
        getContentPane().add(signup64);
        signup64.setBounds(15, 190, 170, 90);

        signup65.setText("SIGN UP");
        getContentPane().add(signup65);
        signup65.setBounds(15, 190, 170, 90);

        signup66.setText("SIGN UP");
        getContentPane().add(signup66);
        signup66.setBounds(15, 190, 170, 90);

        signup67.setText("SIGN UP");
        getContentPane().add(signup67);
        signup67.setBounds(15, 190, 170, 90);

        signup68.setText("SIGN UP");
        getContentPane().add(signup68);
        signup68.setBounds(15, 190, 170, 90);

        signup69.setText("SIGN UP");
        getContentPane().add(signup69);
        signup69.setBounds(15, 190, 170, 90);

        signup70.setText("SIGN UP");
        getContentPane().add(signup70);
        signup70.setBounds(15, 190, 170, 90);

        signup71.setText("SIGN UP");
        getContentPane().add(signup71);
        signup71.setBounds(15, 190, 170, 90);

        signup72.setText("SIGN UP");
        getContentPane().add(signup72);
        signup72.setBounds(15, 190, 170, 90);

        signup73.setText("SIGN UP");
        getContentPane().add(signup73);
        signup73.setBounds(15, 190, 170, 90);

        signup74.setText("SIGN UP");
        getContentPane().add(signup74);
        signup74.setBounds(15, 190, 170, 90);

        signup75.setText("SIGN UP");
        getContentPane().add(signup75);
        signup75.setBounds(15, 190, 170, 90);

        signup76.setText("SIGN UP");
        getContentPane().add(signup76);
        signup76.setBounds(15, 190, 170, 90);

        signup77.setText("SIGN UP");
        getContentPane().add(signup77);
        signup77.setBounds(15, 190, 170, 90);

        signup78.setText("SIGN UP");
        getContentPane().add(signup78);
        signup78.setBounds(15, 190, 170, 90);

        signup79.setText("SIGN UP");
        getContentPane().add(signup79);
        signup79.setBounds(15, 190, 170, 90);

        signup80.setText("SIGN UP");
        getContentPane().add(signup80);
        signup80.setBounds(15, 190, 170, 90);

        signup81.setText("SIGN UP");
        getContentPane().add(signup81);
        signup81.setBounds(15, 190, 170, 90);

        signup82.setText("SIGN UP");
        getContentPane().add(signup82);
        signup82.setBounds(15, 190, 170, 90);

        signup83.setText("SIGN UP");
        getContentPane().add(signup83);
        signup83.setBounds(15, 190, 170, 90);

        signup84.setText("SIGN UP");
        getContentPane().add(signup84);
        signup84.setBounds(15, 190, 170, 90);

        signup85.setText("SIGN UP");
        getContentPane().add(signup85);
        signup85.setBounds(15, 190, 170, 90);

        signup86.setText("SIGN UP");
        getContentPane().add(signup86);
        signup86.setBounds(15, 190, 170, 90);

        signup87.setText("SIGN UP");
        getContentPane().add(signup87);
        signup87.setBounds(15, 190, 170, 90);

        signup88.setText("SIGN UP");
        getContentPane().add(signup88);
        signup88.setBounds(15, 190, 170, 90);

        signup89.setText("SIGN UP");
        getContentPane().add(signup89);
        signup89.setBounds(15, 190, 170, 90);

        signup90.setText("SIGN UP");
        getContentPane().add(signup90);
        signup90.setBounds(15, 190, 170, 90);

        signup91.setText("SIGN UP");
        getContentPane().add(signup91);
        signup91.setBounds(15, 190, 170, 90);

        signup92.setText("SIGN UP");
        getContentPane().add(signup92);
        signup92.setBounds(15, 190, 170, 90);

        signup93.setText("SIGN UP");
        getContentPane().add(signup93);
        signup93.setBounds(15, 190, 170, 90);

        signup94.setText("SIGN UP");
        getContentPane().add(signup94);
        signup94.setBounds(15, 190, 170, 90);

        signup95.setText("SIGN UP");
        getContentPane().add(signup95);
        signup95.setBounds(15, 190, 170, 90);

        signup96.setText("SIGN UP");
        getContentPane().add(signup96);
        signup96.setBounds(15, 190, 170, 90);

        signup97.setText("SIGN UP");
        getContentPane().add(signup97);
        signup97.setBounds(15, 190, 170, 90);

        signup98.setText("SIGN UP");
        getContentPane().add(signup98);
        signup98.setBounds(15, 190, 170, 90);

        signup99.setText("SIGN UP");
        getContentPane().add(signup99);
        signup99.setBounds(15, 190, 170, 90);

        signup100.setText("SIGN UP");
        getContentPane().add(signup100);
        signup100.setBounds(15, 190, 170, 90);

        signup101.setText("SIGN UP");
        getContentPane().add(signup101);
        signup101.setBounds(15, 190, 170, 90);

        signup102.setText("SIGN UP");
        getContentPane().add(signup102);
        signup102.setBounds(15, 190, 170, 90);

        signup103.setText("SIGN UP");
        getContentPane().add(signup103);
        signup103.setBounds(15, 190, 170, 90);

        signup104.setText("SIGN UP");
        getContentPane().add(signup104);
        signup104.setBounds(15, 190, 170, 90);

        signup105.setText("SIGN UP");
        getContentPane().add(signup105);
        signup105.setBounds(15, 190, 170, 90);

        signup106.setText("SIGN UP");
        getContentPane().add(signup106);
        signup106.setBounds(15, 190, 170, 90);

        signup107.setText("SIGN UP");
        getContentPane().add(signup107);
        signup107.setBounds(15, 190, 170, 90);

        signup108.setText("SIGN UP");
        getContentPane().add(signup108);
        signup108.setBounds(15, 190, 170, 90);

        signup109.setText("SIGN UP");
        getContentPane().add(signup109);
        signup109.setBounds(15, 190, 170, 90);

        signup110.setText("SIGN UP");
        getContentPane().add(signup110);
        signup110.setBounds(15, 190, 170, 90);

        signup111.setText("SIGN UP");
        getContentPane().add(signup111);
        signup111.setBounds(15, 190, 170, 90);

        signup112.setText("SIGN UP");
        getContentPane().add(signup112);
        signup112.setBounds(15, 190, 170, 90);

        signup113.setText("SIGN UP");
        getContentPane().add(signup113);
        signup113.setBounds(15, 190, 170, 90);

        signup114.setText("SIGN UP");
        getContentPane().add(signup114);
        signup114.setBounds(15, 190, 170, 90);

        signup115.setText("SIGN UP");
        getContentPane().add(signup115);
        signup115.setBounds(15, 190, 170, 90);

        signup116.setText("SIGN UP");
        getContentPane().add(signup116);
        signup116.setBounds(15, 190, 170, 90);

        signup117.setText("SIGN UP");
        getContentPane().add(signup117);
        signup117.setBounds(15, 190, 170, 90);

        signup118.setText("SIGN UP");
        getContentPane().add(signup118);
        signup118.setBounds(15, 190, 170, 90);

        signup119.setText("SIGN UP");
        getContentPane().add(signup119);
        signup119.setBounds(15, 190, 170, 90);

        signup120.setText("SIGN UP");
        getContentPane().add(signup120);
        signup120.setBounds(15, 190, 170, 90);

        signup121.setText("SIGN UP");
        getContentPane().add(signup121);
        signup121.setBounds(15, 190, 170, 90);

        signup122.setText("SIGN UP");
        getContentPane().add(signup122);
        signup122.setBounds(15, 190, 170, 90);

        signup123.setText("SIGN UP");
        getContentPane().add(signup123);
        signup123.setBounds(15, 190, 170, 90);

        signup124.setText("SIGN UP");
        getContentPane().add(signup124);
        signup124.setBounds(15, 190, 170, 90);

        signup125.setText("SIGN UP");
        getContentPane().add(signup125);
        signup125.setBounds(15, 190, 170, 90);

        signup126.setText("SIGN UP");
        getContentPane().add(signup126);
        signup126.setBounds(15, 190, 170, 90);

        signup127.setText("SIGN UP");
        getContentPane().add(signup127);
        signup127.setBounds(15, 190, 170, 90);

        signup128.setText("SIGN UP");
        getContentPane().add(signup128);
        signup128.setBounds(15, 190, 170, 90);

        signup129.setText("SIGN UP");
        getContentPane().add(signup129);
        signup129.setBounds(15, 190, 170, 90);

        signup130.setText("SIGN UP");
        getContentPane().add(signup130);
        signup130.setBounds(15, 190, 170, 90);

        signup131.setText("SIGN UP");
        getContentPane().add(signup131);
        signup131.setBounds(15, 190, 170, 90);

        signup132.setText("SIGN UP");
        getContentPane().add(signup132);
        signup132.setBounds(15, 190, 170, 90);

        signup133.setText("SIGN UP");
        getContentPane().add(signup133);
        signup133.setBounds(15, 190, 170, 90);

        signup134.setText("SIGN UP");
        getContentPane().add(signup134);
        signup134.setBounds(15, 190, 170, 90);

        signup135.setText("SIGN UP");
        getContentPane().add(signup135);
        signup135.setBounds(15, 190, 170, 90);

        signup136.setText("SIGN UP");
        getContentPane().add(signup136);
        signup136.setBounds(15, 190, 170, 90);

        signup137.setText("SIGN UP");
        getContentPane().add(signup137);
        signup137.setBounds(15, 190, 170, 90);

        signup138.setText("SIGN UP");
        getContentPane().add(signup138);
        signup138.setBounds(15, 190, 170, 90);

        signup139.setText("SIGN UP");
        getContentPane().add(signup139);
        signup139.setBounds(15, 190, 170, 90);

        signup140.setText("SIGN UP");
        getContentPane().add(signup140);
        signup140.setBounds(15, 190, 170, 90);

        signup141.setText("SIGN UP");
        getContentPane().add(signup141);
        signup141.setBounds(15, 190, 170, 90);

        signup142.setText("SIGN UP");
        getContentPane().add(signup142);
        signup142.setBounds(15, 190, 170, 90);

        signup143.setText("SIGN UP");
        getContentPane().add(signup143);
        signup143.setBounds(15, 190, 170, 90);

        signup144.setText("SIGN UP");
        getContentPane().add(signup144);
        signup144.setBounds(15, 190, 170, 90);

        signup145.setText("SIGN UP");
        getContentPane().add(signup145);
        signup145.setBounds(15, 190, 170, 90);

        signup146.setText("SIGN UP");
        getContentPane().add(signup146);
        signup146.setBounds(15, 190, 170, 90);

        signup147.setText("SIGN UP");
        getContentPane().add(signup147);
        signup147.setBounds(15, 190, 170, 90);

        signup148.setText("SIGN UP");
        getContentPane().add(signup148);
        signup148.setBounds(15, 190, 170, 90);

        signup149.setText("SIGN UP");
        getContentPane().add(signup149);
        signup149.setBounds(15, 190, 170, 90);

        signup150.setText("SIGN UP");
        getContentPane().add(signup150);
        signup150.setBounds(15, 190, 170, 90);

        signup151.setText("SIGN UP");
        getContentPane().add(signup151);
        signup151.setBounds(15, 190, 170, 90);

        signup152.setText("SIGN UP");
        getContentPane().add(signup152);
        signup152.setBounds(15, 190, 170, 90);

        signup153.setText("SIGN UP");
        getContentPane().add(signup153);
        signup153.setBounds(15, 190, 170, 90);

        signup154.setText("SIGN UP");
        getContentPane().add(signup154);
        signup154.setBounds(15, 190, 170, 90);

        signup155.setText("SIGN UP");
        getContentPane().add(signup155);
        signup155.setBounds(15, 190, 170, 90);

        signup156.setText("SIGN UP");
        getContentPane().add(signup156);
        signup156.setBounds(15, 190, 170, 90);

        signup157.setText("SIGN UP");
        getContentPane().add(signup157);
        signup157.setBounds(15, 190, 170, 90);

        signup158.setText("SIGN UP");
        getContentPane().add(signup158);
        signup158.setBounds(15, 190, 170, 90);

        signup159.setText("SIGN UP");
        getContentPane().add(signup159);
        signup159.setBounds(15, 190, 170, 90);

        signup160.setText("SIGN UP");
        getContentPane().add(signup160);
        signup160.setBounds(15, 190, 170, 90);

        signup161.setText("SIGN UP");
        getContentPane().add(signup161);
        signup161.setBounds(15, 190, 170, 90);

        signup162.setText("SIGN UP");
        getContentPane().add(signup162);
        signup162.setBounds(15, 190, 170, 90);

        signup163.setText("SIGN UP");
        getContentPane().add(signup163);
        signup163.setBounds(15, 190, 170, 90);

        signup164.setText("SIGN UP");
        getContentPane().add(signup164);
        signup164.setBounds(15, 190, 170, 90);

        signup165.setText("SIGN UP");
        getContentPane().add(signup165);
        signup165.setBounds(15, 190, 170, 90);

        signup166.setText("SIGN UP");
        getContentPane().add(signup166);
        signup166.setBounds(15, 190, 170, 90);

        signup167.setText("SIGN UP");
        getContentPane().add(signup167);
        signup167.setBounds(15, 190, 170, 90);

        signup168.setText("SIGN UP");
        getContentPane().add(signup168);
        signup168.setBounds(15, 190, 170, 90);

        signup169.setText("SIGN UP");
        getContentPane().add(signup169);
        signup169.setBounds(15, 190, 170, 90);

        signup170.setText("SIGN UP");
        getContentPane().add(signup170);
        signup170.setBounds(15, 190, 170, 90);

        signup171.setText("SIGN UP");
        getContentPane().add(signup171);
        signup171.setBounds(15, 190, 170, 90);

        signup172.setText("SIGN UP");
        getContentPane().add(signup172);
        signup172.setBounds(15, 190, 170, 90);

        signup173.setText("SIGN UP");
        getContentPane().add(signup173);
        signup173.setBounds(15, 190, 170, 90);

        signup174.setText("SIGN UP");
        getContentPane().add(signup174);
        signup174.setBounds(15, 190, 170, 90);

        signup175.setText("SIGN UP");
        getContentPane().add(signup175);
        signup175.setBounds(15, 190, 170, 90);

        signup176.setText("SIGN UP");
        getContentPane().add(signup176);
        signup176.setBounds(15, 190, 170, 90);

        signup177.setText("SIGN UP");
        getContentPane().add(signup177);
        signup177.setBounds(15, 190, 170, 90);

        signup178.setText("SIGN UP");
        getContentPane().add(signup178);
        signup178.setBounds(15, 190, 170, 90);

        signup179.setText("SIGN UP");
        getContentPane().add(signup179);
        signup179.setBounds(15, 190, 170, 90);

        signup180.setText("SIGN UP");
        getContentPane().add(signup180);
        signup180.setBounds(15, 190, 170, 90);

        signup181.setText("SIGN UP");
        getContentPane().add(signup181);
        signup181.setBounds(15, 190, 170, 90);

        signup182.setText("SIGN UP");
        getContentPane().add(signup182);
        signup182.setBounds(15, 190, 170, 90);

        signup183.setText("SIGN UP");
        getContentPane().add(signup183);
        signup183.setBounds(15, 190, 170, 90);

        signup184.setText("SIGN UP");
        getContentPane().add(signup184);
        signup184.setBounds(15, 190, 170, 90);

        signup185.setText("SIGN UP");
        getContentPane().add(signup185);
        signup185.setBounds(15, 190, 170, 90);

        signup186.setText("SIGN UP");
        getContentPane().add(signup186);
        signup186.setBounds(15, 190, 170, 90);

        signup187.setText("SIGN UP");
        getContentPane().add(signup187);
        signup187.setBounds(15, 190, 170, 90);

        signup188.setText("SIGN UP");
        getContentPane().add(signup188);
        signup188.setBounds(15, 190, 170, 90);

        signup189.setText("SIGN UP");
        getContentPane().add(signup189);
        signup189.setBounds(15, 190, 170, 90);

        signup190.setText("SIGN UP");
        getContentPane().add(signup190);
        signup190.setBounds(15, 190, 170, 90);

        signup191.setText("SIGN UP");
        getContentPane().add(signup191);
        signup191.setBounds(15, 190, 170, 90);

        signup192.setText("SIGN UP");
        getContentPane().add(signup192);
        signup192.setBounds(15, 190, 170, 90);

        signup193.setText("SIGN UP");
        getContentPane().add(signup193);
        signup193.setBounds(15, 190, 170, 90);

        signup194.setText("SIGN UP");
        getContentPane().add(signup194);
        signup194.setBounds(15, 190, 170, 90);

        signup195.setText("SIGN UP");
        getContentPane().add(signup195);
        signup195.setBounds(15, 190, 170, 90);

        signup196.setText("SIGN UP");
        getContentPane().add(signup196);
        signup196.setBounds(15, 190, 170, 90);

        signup197.setText("SIGN UP");
        getContentPane().add(signup197);
        signup197.setBounds(15, 190, 170, 90);

        signup198.setText("SIGN UP");
        getContentPane().add(signup198);
        signup198.setBounds(15, 190, 170, 90);

        signup199.setText("SIGN UP");
        getContentPane().add(signup199);
        signup199.setBounds(15, 190, 170, 90);

        signup200.setText("SIGN UP");
        getContentPane().add(signup200);
        signup200.setBounds(15, 190, 170, 90);

        signup201.setText("SIGN UP");
        getContentPane().add(signup201);
        signup201.setBounds(15, 190, 170, 90);

        signup202.setText("SIGN UP");
        getContentPane().add(signup202);
        signup202.setBounds(15, 190, 170, 90);

        signup203.setText("SIGN UP");
        getContentPane().add(signup203);
        signup203.setBounds(15, 190, 170, 90);

        signup204.setText("SIGN UP");
        getContentPane().add(signup204);
        signup204.setBounds(15, 190, 170, 90);

        userlogin.setBackground(new java.awt.Color(102, 102, 102));
        userlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userlogin.setForeground(new java.awt.Color(204, 204, 204));
        userlogin.setText("USER LOGIN");
        userlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userloginActionPerformed(evt);
            }
        });
        getContentPane().add(userlogin);
        userlogin.setBounds(340, 190, 170, 90);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 90);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Made By:-  BHAVESH UPPAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 400, 440, 60);
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userloginActionPerformed
        // TODO add your handling code here:
        userlogin obj=new userlogin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_userloginActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
        Admin_login obj=new Admin_login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton signup1;
    private javax.swing.JButton signup10;
    private javax.swing.JButton signup100;
    private javax.swing.JButton signup101;
    private javax.swing.JButton signup102;
    private javax.swing.JButton signup103;
    private javax.swing.JButton signup104;
    private javax.swing.JButton signup105;
    private javax.swing.JButton signup106;
    private javax.swing.JButton signup107;
    private javax.swing.JButton signup108;
    private javax.swing.JButton signup109;
    private javax.swing.JButton signup11;
    private javax.swing.JButton signup110;
    private javax.swing.JButton signup111;
    private javax.swing.JButton signup112;
    private javax.swing.JButton signup113;
    private javax.swing.JButton signup114;
    private javax.swing.JButton signup115;
    private javax.swing.JButton signup116;
    private javax.swing.JButton signup117;
    private javax.swing.JButton signup118;
    private javax.swing.JButton signup119;
    private javax.swing.JButton signup12;
    private javax.swing.JButton signup120;
    private javax.swing.JButton signup121;
    private javax.swing.JButton signup122;
    private javax.swing.JButton signup123;
    private javax.swing.JButton signup124;
    private javax.swing.JButton signup125;
    private javax.swing.JButton signup126;
    private javax.swing.JButton signup127;
    private javax.swing.JButton signup128;
    private javax.swing.JButton signup129;
    private javax.swing.JButton signup13;
    private javax.swing.JButton signup130;
    private javax.swing.JButton signup131;
    private javax.swing.JButton signup132;
    private javax.swing.JButton signup133;
    private javax.swing.JButton signup134;
    private javax.swing.JButton signup135;
    private javax.swing.JButton signup136;
    private javax.swing.JButton signup137;
    private javax.swing.JButton signup138;
    private javax.swing.JButton signup139;
    private javax.swing.JButton signup14;
    private javax.swing.JButton signup140;
    private javax.swing.JButton signup141;
    private javax.swing.JButton signup142;
    private javax.swing.JButton signup143;
    private javax.swing.JButton signup144;
    private javax.swing.JButton signup145;
    private javax.swing.JButton signup146;
    private javax.swing.JButton signup147;
    private javax.swing.JButton signup148;
    private javax.swing.JButton signup149;
    private javax.swing.JButton signup15;
    private javax.swing.JButton signup150;
    private javax.swing.JButton signup151;
    private javax.swing.JButton signup152;
    private javax.swing.JButton signup153;
    private javax.swing.JButton signup154;
    private javax.swing.JButton signup155;
    private javax.swing.JButton signup156;
    private javax.swing.JButton signup157;
    private javax.swing.JButton signup158;
    private javax.swing.JButton signup159;
    private javax.swing.JButton signup16;
    private javax.swing.JButton signup160;
    private javax.swing.JButton signup161;
    private javax.swing.JButton signup162;
    private javax.swing.JButton signup163;
    private javax.swing.JButton signup164;
    private javax.swing.JButton signup165;
    private javax.swing.JButton signup166;
    private javax.swing.JButton signup167;
    private javax.swing.JButton signup168;
    private javax.swing.JButton signup169;
    private javax.swing.JButton signup17;
    private javax.swing.JButton signup170;
    private javax.swing.JButton signup171;
    private javax.swing.JButton signup172;
    private javax.swing.JButton signup173;
    private javax.swing.JButton signup174;
    private javax.swing.JButton signup175;
    private javax.swing.JButton signup176;
    private javax.swing.JButton signup177;
    private javax.swing.JButton signup178;
    private javax.swing.JButton signup179;
    private javax.swing.JButton signup18;
    private javax.swing.JButton signup180;
    private javax.swing.JButton signup181;
    private javax.swing.JButton signup182;
    private javax.swing.JButton signup183;
    private javax.swing.JButton signup184;
    private javax.swing.JButton signup185;
    private javax.swing.JButton signup186;
    private javax.swing.JButton signup187;
    private javax.swing.JButton signup188;
    private javax.swing.JButton signup189;
    private javax.swing.JButton signup19;
    private javax.swing.JButton signup190;
    private javax.swing.JButton signup191;
    private javax.swing.JButton signup192;
    private javax.swing.JButton signup193;
    private javax.swing.JButton signup194;
    private javax.swing.JButton signup195;
    private javax.swing.JButton signup196;
    private javax.swing.JButton signup197;
    private javax.swing.JButton signup198;
    private javax.swing.JButton signup199;
    private javax.swing.JButton signup2;
    private javax.swing.JButton signup20;
    private javax.swing.JButton signup200;
    private javax.swing.JButton signup201;
    private javax.swing.JButton signup202;
    private javax.swing.JButton signup203;
    private javax.swing.JButton signup204;
    private javax.swing.JButton signup21;
    private javax.swing.JButton signup22;
    private javax.swing.JButton signup23;
    private javax.swing.JButton signup24;
    private javax.swing.JButton signup25;
    private javax.swing.JButton signup26;
    private javax.swing.JButton signup27;
    private javax.swing.JButton signup28;
    private javax.swing.JButton signup29;
    private javax.swing.JButton signup3;
    private javax.swing.JButton signup30;
    private javax.swing.JButton signup31;
    private javax.swing.JButton signup32;
    private javax.swing.JButton signup33;
    private javax.swing.JButton signup34;
    private javax.swing.JButton signup35;
    private javax.swing.JButton signup36;
    private javax.swing.JButton signup37;
    private javax.swing.JButton signup38;
    private javax.swing.JButton signup39;
    private javax.swing.JButton signup4;
    private javax.swing.JButton signup40;
    private javax.swing.JButton signup41;
    private javax.swing.JButton signup42;
    private javax.swing.JButton signup43;
    private javax.swing.JButton signup44;
    private javax.swing.JButton signup45;
    private javax.swing.JButton signup46;
    private javax.swing.JButton signup47;
    private javax.swing.JButton signup48;
    private javax.swing.JButton signup49;
    private javax.swing.JButton signup5;
    private javax.swing.JButton signup50;
    private javax.swing.JButton signup51;
    private javax.swing.JButton signup52;
    private javax.swing.JButton signup53;
    private javax.swing.JButton signup54;
    private javax.swing.JButton signup55;
    private javax.swing.JButton signup56;
    private javax.swing.JButton signup57;
    private javax.swing.JButton signup58;
    private javax.swing.JButton signup59;
    private javax.swing.JButton signup6;
    private javax.swing.JButton signup60;
    private javax.swing.JButton signup61;
    private javax.swing.JButton signup62;
    private javax.swing.JButton signup63;
    private javax.swing.JButton signup64;
    private javax.swing.JButton signup65;
    private javax.swing.JButton signup66;
    private javax.swing.JButton signup67;
    private javax.swing.JButton signup68;
    private javax.swing.JButton signup69;
    private javax.swing.JButton signup7;
    private javax.swing.JButton signup70;
    private javax.swing.JButton signup71;
    private javax.swing.JButton signup72;
    private javax.swing.JButton signup73;
    private javax.swing.JButton signup74;
    private javax.swing.JButton signup75;
    private javax.swing.JButton signup76;
    private javax.swing.JButton signup77;
    private javax.swing.JButton signup78;
    private javax.swing.JButton signup79;
    private javax.swing.JButton signup8;
    private javax.swing.JButton signup80;
    private javax.swing.JButton signup81;
    private javax.swing.JButton signup82;
    private javax.swing.JButton signup83;
    private javax.swing.JButton signup84;
    private javax.swing.JButton signup85;
    private javax.swing.JButton signup86;
    private javax.swing.JButton signup87;
    private javax.swing.JButton signup88;
    private javax.swing.JButton signup89;
    private javax.swing.JButton signup9;
    private javax.swing.JButton signup90;
    private javax.swing.JButton signup91;
    private javax.swing.JButton signup92;
    private javax.swing.JButton signup93;
    private javax.swing.JButton signup94;
    private javax.swing.JButton signup95;
    private javax.swing.JButton signup96;
    private javax.swing.JButton signup97;
    private javax.swing.JButton signup98;
    private javax.swing.JButton signup99;
    private javax.swing.JButton userlogin;
    // End of variables declaration//GEN-END:variables
}
